InventarioUX/Controllers/CarritoEntradaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using InventarioUX.Models;
using Rotativa;

namespace InventarioUX.Controllers
{
    public class CarritoEntradaController : Controller
    {
        private ConnectionContext db = new ConnectionContext();

        /////////
        ///////// Lista de movimientos
        /////////
        public ActionResult Index()
        {
            var mOV_ENTRADA = db.MOV_ENTRADA.Include(m => m.CONTAINING_EMPLEADOS).Include(m => m.CONTAINING_PROVEEDORES);
            return View(mOV_ENTRADA.ToList());
        }

        /////////
        ///////// Detalles de un movimiento
        /////////
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MOV_ENTRADA mOV_ENTRADA = db.MOV_ENTRADA.Find(id);
            if (mOV_ENTRADA == null)
            {
                return HttpNotFound();
            }
            List<int> result = new List<int>();
            var con = new SqlConnection("Data Source=DESKTOP-I5C9AA0\\SQLEXPRESS2008;Initial Catalog=InventarioUXBD;Integrated Security=True");
            con.Open();
            var command = new SqlCommand("SELECT ID FROM MOV_ENTRADA_LISTA WHERE MOV_ENTRADAID='" + id + "'", con);
            SqlDataReader reader = command.ExecuteReader();
            while (reader.Read())
            {
                result.Add(Convert.ToInt32(reader["ID"]));
            }
            List<MOV_ENTRADA_LISTA> listaProductos = new List<MOV_ENTRADA_LISTA>();
            int i = 0;
            foreach (var w in result)
            {
                var x = db.MOV_ENTRADA_LISTA.Find(result[i]);
                MOV_ENTRADA_LISTA x2 = new MOV_ENTRADA_LISTA();
                x2.CONTAINING_PRODUCTOS = x.CONTAINING_PRODUCTOS;
                x2.PRECIO = x.PRECIO;
                x2.CANTIDAD = x.CANTIDAD;
                listaProductos.Add(x2);
                i++;
            }
            ViewBag.ListaEntrada = listaProductos;
            return View(mOV_ENTRADA);
        }

        /////////
        ///////// Seleccion de productos
        /////////
        public ActionResult SelectProducto(FormCollection fc)
        {
            return View();
        }

        /////////
        ///////// Recibe un codigo de barras y lo busca, redirecciona a "Agregar" el id correspondiente a ese codigo de barras
        /////////
        public ActionResult codigobarras(FormCollection fc)
        {
            var con = new SqlConnection("Data Source=DESKTOP-I5C9AA0\\SQLEXPRESS2008;Initial Catalog=InventarioUXBD;Integrated Security=True");
            con.Open();

            string[] cantidad = fc.GetValues("codigobarras");
            //int codigobarras = Convert.ToInt32(cantidad[0]);

            var command = new SqlCommand("SELECT ID FROM dbo.PRODUCTOS WHERE CODIGOBARRAS='"+ cantidad[0] + "'", con);
            try
            {
                int id = (int)(command.ExecuteScalar());
                return RedirectToAction("Agregar", new { id = id });
            }
            catch
            {
                ViewBag.Error = true;
                return View("Carrito");
            }
        }

        /////////
        /////////
        /////////
        public ActionResult Carrito()
        {
            return View();
        }

        /////////
        /////////
        /////////
        private int isExisting(int id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            for (int i = 0; i < cart.Count(); i++)
            {
                if (cart[i].Producto.ID == id)
                    return i;

            }
            return -1;
        }

        /////////
        ///////// Elimina un producto
        /////////
        public ActionResult Eliminar(int id)
        {
            int index = isExisting(id);
            List<Item> cart = (List<Item>)Session["cart"];
            cart.RemoveAt(index);
            Session["cart"] = cart;
            return View("Carrito");
        }

        /////////
        ///////// Agrega el producto seleccionado en "codigobarras" al carrito
        /////////
        public ActionResult Agregar(int id)
        {
            if (Session["cart"] == null)
            {
                List<Item> cart = new List<Item>();
                var wea = db.PRODUCTOS.Find(id);
                Item wea2 = new Item();
                wea2.Producto = wea;
                wea2.Cantidad = 1;
                cart.Add(wea2);
                Session["cart"] = cart;
            }
            else
            {
                List<Item> cart = (List<Item>)Session["cart"];
                int index = isExisting(id);
                if (index == -1)
                {
                    var wea = db.PRODUCTOS.Find(id);
                    Item wea2 = new Item();
                    wea2.Producto = wea;
                    wea2.Cantidad = 1;
                    cart.Add(wea2);
                }
                else
                {
                    cart[index].Cantidad++;
                }

                Session["cart"] = cart;
            }
            return View("Carrito");
        }


        /////////
        ///////// Selecciona un proveedor
        /////////
        public ActionResult CheckOut()
        {
            ViewBag.PROVEEDORID = new SelectList(db.PROVEEDORES, "ID", "NOMBRE");

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Checkout([Bind(Include = "PROVEEDORID")] MOV_ENTRADA mov_entrada)
        {
            Session["Proveedor"] = mov_entrada.PROVEEDORID;
            return View("Carrito"); 
        }

        /////////
        /////////Registro del movimiento y cada producto en el
        /////////
        public ActionResult Registro()
        {
            MOV_ENTRADA mov_entrada = new MOV_ENTRADA();
            List<Item> cart = (List<Item>)Session["cart"];
            int preciototal = 0;
            mov_entrada.EMPLEADOID = int.Parse(Session["ID"].ToString());
            mov_entrada.PROVEEDORID = int.Parse(Session["Proveedor"].ToString()); ;
            mov_entrada.Fecha = DateTime.Now;
            db.MOV_ENTRADA.Add(mov_entrada);
            db.SaveChanges();

            foreach (Item item in cart)
            {
                var con = new SqlConnection("Data Source=DESKTOP-I5C9AA0\\SQLEXPRESS2008;Initial Catalog=InventarioUXBD;Integrated Security=True");
                con.Open();
                MOV_ENTRADA_LISTA mov_entrada_lista = new MOV_ENTRADA_LISTA();
                mov_entrada_lista.PRODUCTOID = item.Producto.ID;
                mov_entrada_lista.CANTIDAD = item.Cantidad;
                mov_entrada_lista.PRECIO = item.Producto.PRECIO;
                preciototal = preciototal + (item.Producto.PRECIO * item.Cantidad);
                mov_entrada_lista.MOV_ENTRADAID = mov_entrada.ID;
                db.MOV_ENTRADA_LISTA.Add(mov_entrada_lista);
                db.SaveChanges();

                SqlCommand command = new SqlCommand("UPDATE PRODUCTOS SET CANTIDAD = CANTIDAD + " + item.Cantidad + " WHERE ID = " + item.Producto.ID + "", con);
                command.ExecuteNonQuery();
            }
            mov_entrada.PRECIOTOTAL = preciototal;
            db.SaveChanges();
            Session.Remove("Proveedor");
            Session.Remove("cart");
            preciototal = 0;
            return View();
        }

        public ActionResult Cancelar()
        {
            return View("");
        }

        public ActionResult Update(FormCollection fc)
        {
            string[] cantidades = fc.GetValues("Cantidad");
            List<Item> cart = (List<Item>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
            {
                cart[i].Cantidad = Convert.ToInt32(cantidades[i]);
            }
            return View("Carrito");
        }

        public ActionResult ReciboEntrada (int? id){
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            MOV_ENTRADA mOV_ENTRADA = db.MOV_ENTRADA.Find(id);
            if (mOV_ENTRADA == null)
            {
                return HttpNotFound();
            }
            List<int> result = new List<int>();
            var con = new SqlConnection("Data Source=DESKTOP-I5C9AA0\\SQLEXPRESS2008;Initial Catalog=InventarioUXBD;Integrated Security=True");
            con.Open();
            var command = new SqlCommand("SELECT ID FROM MOV_ENTRADA_LISTA WHERE MOV_ENTRADAID='" + id + "'", con);
            SqlDataReader reader = command.ExecuteReader();
            while (reader.Read())
            {
                result.Add(Convert.ToInt32(reader["ID"]));
            }
            List<MOV_ENTRADA_LISTA> listaProductos = new List<MOV_ENTRADA_LISTA>();
            int i = 0;
            foreach (var w in result)
            {
                var x = db.MOV_ENTRADA_LISTA.Find(result[i]);
                MOV_ENTRADA_LISTA x2 = new MOV_ENTRADA_LISTA();
                x2.CONTAINING_PRODUCTOS = x.CONTAINING_PRODUCTOS;
                x2.PRECIO = x.PRECIO;
                x2.CANTIDAD = x.CANTIDAD;
                listaProductos.Add(x2);
                i++;
            }
            ViewBag.ListaEntrada = listaProductos;
            return View(mOV_ENTRADA);
        }

        public ActionResult ExportPDF(int? id)
        {
            return new ActionAsPdf("ReciboEntrada", new { id = id })
            {
                FileName = Server.MapPath("~/Content/Relato.pdf"),
                PageOrientation = Rotativa.Options.Orientation.Landscape,
                PageSize = Rotativa.Options.Size.A4
            };
        }
    }

}

InventarioUX/Views/CarritoEntrada/Carrito.cshtml
@using InventarioUX.Controllers
@{
    ViewBag.Title = "Carrito";
}

<div>
    @Html.Partial("SelectProducto")
</div>

<h1>              </h1>
<h1>              </h1>

<table class="table">
    @using (Html.BeginForm("Update", "CarritoEntrada", FormMethod.Post))
    {
    <input type="submit" class="btn btn-default" value="Actualizar cantidades" />
    <tr>
        <th>Eliminar</th>
        <th>ID</th>
        <th>Nombre</th>
        <th>Precio</th>
        <th>Cantidad</th>
        <th>Subtotal</th>
    </tr>
        if (Session["cart"] != null)
        {
            foreach (Item item in (List<Item>)Session["cart"])
            {
                <tr>
                    <th><button class="btn btn-default">@Html.ActionLink("Eliminar", "Eliminar", "CarritoEntrada", new { id = item.Producto.ID })</button></th>
                    <th>@item.Producto.ID</th>
                    <th>@item.Producto.NOMBRE</th>
                    <th>@item.Producto.PRECIO</th>
                    <th><input type="text" name="Cantidad" , value="@item.Cantidad" /></th>
                    <th>@(item.Producto.PRECIO * item.Cantidad)</th>
                </tr>
            }
        }
        else
        {
            <tr>
                <th> </th>
                <th> </th>
                <th> </th>
                <th> </th>
                <th> </th>
                <th> </th>
            </tr>
        }
    }
</table>

<button class="btn btn-default">@Html.ActionLink("Generar Entrada", "Registro", "CarritoEntrada", new { data_toggle = "modal", data_target = "#modalS" })</button>
<button class="btn btn-default">@Html.ActionLink("Cancelar Movimiento", "Index", "Account")</button>

<script src="~/Scripts/sweetalert2.js"></script>
<script src="~/Scripts/sweetalert2.min.js"></script>
<link href="~/Scripts/sweetalert2.css" rel="stylesheet"/>
@if (ViewBag.Error == true)
{
    <script>
        window.onload = function () {
            swal(
                '¡El codigo de barras no existe!',
                'Ingrese un codigo de barras valido',
                'error'
            )
        };
    </script>
}



<div class="modal fade" id="modalS" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        @using (Html.BeginForm())
        {
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Entradas</h4>
                </div>
                <div class="modal-body">
                    @Html.Partial("OrderSaved")
                </div>
                <div class="modal-footer">

                </div>
            </div>
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/Scripts/sweetalert2.min.js")
}

InventarioUX/Views/CarritoEntrada/CheckOut.cshtml
@model InventarioUX.Models.MOV_ENTRADA
@{
    ViewBag.Title = "CheckOut";
}

<h2>Seleccione un proveedor</h2>


        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger"})
            <table class="table">
                <tr>
                    <td>@Html.LabelFor(model => model.PROVEEDORID, "PROVEEDOR", htmlAttributes: new { @class = "control-label col-md-2"})</td>
                    <td>@Html.DropDownList("PROVEEDORID", null, htmlAttributes: new { @class = "form-control" })</td>
                    @Html.ValidationMessageFor(model => model.PROVEEDORID, "", new { @class = "text-danger" })
                </tr>
                <tr>
                    <td>     </td>
                    <td><input type="submit" value="Ingresar"/></td>
                </tr>
            </table>
        }

InventarioUX/Views/CarritoEntrada/Details.cshtml
@using InventarioUX.Models
@model InventarioUX.Models.MOV_ENTRADA

@{
    ViewBag.Title = "Details";
}

<style>
    #total {
        text-align: left;
    }
</style>

<div class="panel-default">
    <div class="panel-heading">
        <h3 class="panel-heading">DETALLES DE LA ENTRADA</h3>
        <ul class="dl-horizontal">
            <li>Usuario: @Html.DisplayFor(model => model.CONTAINING_EMPLEADOS.USERNAME)</li>
            <li>Nombre Proveedor:  @Html.DisplayFor(model => model.CONTAINING_PROVEEDORES.NOMBRE)</li>
            <li>Fecha de entrada: @Html.DisplayFor(model => model.Fecha)</li>

        </ul>
    </div>

    <div class="panel-body">
        <table class="table">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Cantidad</th>
                    <th>Precio</th>
                    <th>Subtotal</th>
                </tr>
            </thead>


            @foreach (MOV_ENTRADA_LISTA m in ViewBag.ListaEntrada)
        {
            <tbody>
                <tr>
                    <th>@m.CONTAINING_PRODUCTOS.NOMBRE</th>
                    <th>@m.CANTIDAD</th>
                    <th>@m.PRECIO</th>
                    <th>@(m.PRECIO * m.CANTIDAD)</th>
                </tr>
            </tbody>
    }

            <tfoot>
                <tr>
                    <th>Total</th>
                    <th colspan="2"></th>
                    <th id="total" colspan="2">@Html.DisplayFor(model => model.PRECIOTOTAL)</th>
                </tr>
            </tfoot>

        </table>
    </div>
    <p>
        @Html.ActionLink("Regresar al registro", "Index", new { area = "" }, new { @class = "btn btn-danger" })
    </p>
</div>

InventarioUX/Views/CarritoEntrada/Index.cshtml
@model IEnumerable<InventarioUX.Models.MOV_ENTRADA>

@{
    ViewBag.Title = "Index";
}

<div class="navbar navbar-default">
    <div class="nav navbar-var navbar-form">
        <ul class="navbar-right navbar-form">
            <li class="navbar-brand">Entradas de productos:</li>
            <li class="form-group"><div>@Html.ActionLink("Nueva Entrada", "CheckOut", new { area = "" }, new { @class = "btn btn-danger" })</div></li>
        </ul>
        <ul class="navbar-left navbar-form">
            <li class="navbar-brand">Registro de entradas:</li>
        </ul>
    </div>
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CONTAINING_EMPLEADOS.USERNAME)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CONTAINING_PROVEEDORES.NOMBRE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CONTAINING_EMPLEADOS.USERNAME)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CONTAINING_PROVEEDORES.NOMBRE)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha)
            </td>
            <td>
                @Html.ActionLink("Detalles", "Details", new { id = item.ID }) |
                @Html.ActionLink("Generar Recibo", "ExportPDF", new { id = item.ID })
            </td>
        </tr>
    }

</table>

InventarioUX/Views/CarritoEntrada/OrderSaved.cshtml
<h2>Entrada de productos exitosa</h2>

@Html.ActionLink("Aceptar", "Index", "CarritoEntrada", new { @class = "btn btn - success" }) })

InventarioUX/Views/CarritoEntrada/ReciboEntrada.cshtml
@using InventarioUX.Models
@model InventarioUX.Models.MOV_ENTRADA
@{
    Layout = "~/Views/Shared/_LayoutRecibos.cshtml";
}

<div class="panel-default">
    <div class="panel-heading">
        <h4 class="panel-heading">RECIBO</h4>
        <ul class="dl-horizontal">
            <li>Usuario: @Html.DisplayFor(model => model.CONTAINING_EMPLEADOS.USERNAME)</li>
            <li>Nombre Proveedor:  @Html.DisplayFor(model => model.CONTAINING_PROVEEDORES.NOMBRE)</li>
            <li>Fecha de entrada: @Html.DisplayFor(model => model.Fecha)</li>

        </ul>
    </div>

    <div class="panel-body">
        <table class="table">
            <thead>
                <tr>
                    <th>Nombre</th>
                    <th>Cantidad</th>
                    <th>Precio</th>
                    <th>Subtotal</th>
                </tr>
            </thead>


            @foreach (MOV_ENTRADA_LISTA m in ViewBag.ListaEntrada)
            {
                <tbody>
                    <tr>
                        <th>@m.CONTAINING_PRODUCTOS.NOMBRE</th>
                        <th>@m.CANTIDAD</th>
                        <th>@m.PRECIO</th>
                        <th>@(m.PRECIO * m.CANTIDAD)</th>
                    </tr>
                </tbody>
            }

            <tfoot>
                <tr>
                    <th>Total</th>
                    <th colspan="2"></th>
                    <th id="total" colspan="2">@Html.DisplayFor(model => model.PRECIOTOTAL)</th>
                </tr>
            </tfoot>

        </table>
    </div>
</div>

InventarioUX/Views/CarritoEntrada/SelectProducto.cshtml
@model InventarioUX.Models.PRODUCTOS

@using (Html.BeginForm("codigobarras", "CarritoEntrada", FormMethod.Post))
{
<div>
    <h5>Ingresar codigo de barras</h5>
    <input type="text" name="CodigoBarras"/>
    <input type="submit" value="Agregar Producto" class="btn btn-default"/>
</div>
}