InventarioUX/Controllers/CarritoAsignacionController.cs
using InventarioUX.Models;
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data;
using System.Data.Entity;
using System.Net;
using Rotativa;

namespace InventarioUX.Controllers
{
    public class CarritoAsignacionController : Controller
    {
        private ConnectionContext db = new ConnectionContext();

        public ActionResult Index()
        {
            var aSIGNACIONES = db.ASIGNACIONES.Include(a => a.CONTAINING_DEPARTAMENTOS).Include(a => a.CONTAINING_EMPLEADOS);
            return View(aSIGNACIONES.ToList());

        }

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            ASIGNACIONES mOV_ASIGNACION = db.ASIGNACIONES.Find(id);
            if (mOV_ASIGNACION == null)
            {
                return HttpNotFound();
            }
            List<int> result = new List<int>();
            var con = new SqlConnection("Data Source=DESKTOP-I5C9AA0\\SQLEXPRESS2008;Initial Catalog=InventarioUXBD;Integrated Security=True");
            con.Open();
            var command = new SqlCommand("SELECT ID FROM ASIGNACIONES_LISTA WHERE ASIGNACIONID='" + id + "'", con);
            SqlDataReader reader = command.ExecuteReader();
            while (reader.Read())
            {
                result.Add(Convert.ToInt32(reader["ID"]));
            }
            List<ASIGNACIONES_LISTA> listaProductos = new List<ASIGNACIONES_LISTA>();
            int i = 0;
            foreach (var w in result)
            {
                var x = db.ASIGNACIONES_LISTA.Find(result[i]);
                ASIGNACIONES_LISTA x2 = new ASIGNACIONES_LISTA();
                x2.CONTAINING_PRODUCTOS = x.CONTAINING_PRODUCTOS;
                x2.PRECIO = x.PRECIO;
                x2.CANTIDAD = x.CANTIDAD;
                listaProductos.Add(x2);
                i++;
            }
            ViewBag.ListaAsignacion = listaProductos;
            return View(mOV_ASIGNACION);
        }

        public ActionResult SelectProducto(FormCollection fc)
        {
            return View();
        }

        public ActionResult codigobarras(FormCollection fc)
        {
            var con = new SqlConnection("Data Source=DESKTOP-I5C9AA0\\SQLEXPRESS2008;Initial Catalog=InventarioUXBD;Integrated Security=True");
            con.Open();

            string[] cantidad = fc.GetValues("codigobarras");
            string codigobarras = cantidad[0];

            var command = new SqlCommand("SELECT ID FROM dbo.PRODUCTOS WHERE CODIGOBARRAS='" + codigobarras + "'", con);
            try
            {
                int id = (int)(command.ExecuteScalar());
                return RedirectToAction("Agregar", new { id = id });
            }
            catch
            {
                ViewBag.Error = true;
                return View("Carrito");
            }
        }

        public ActionResult Carrito()
        {
            return View();
        }

        private int isExisting(int id)
        {
            List<Item> cart = (List<Item>)Session["cart"];
            for (int i = 0; i < cart.Count(); i++)
            {
                if (cart[i].Producto.ID == id)
                    return i;

            }
            return -1;
        }

        public ActionResult Eliminar(int id)
        {
            int index = isExisting(id);
            List<Item> cart = (List<Item>)Session["cart"];
            cart.RemoveAt(index);
            Session["cart"] = cart;
            return View("Carrito");
        }

        public ActionResult Agregar(int id)
        {
            if (Session["cart"] == null)
            {
                List<Item> cart = new List<Item>();
                var wea = db.PRODUCTOS.Find(id);
                Item wea2 = new Item();
                wea2.Producto = wea;
                wea2.Cantidad = 1;
                cart.Add(wea2);
                Session["cart"] = cart;
            }
            else
            {
                List<Item> cart = (List<Item>)Session["cart"];
                int index = isExisting(id);
                if (index == -1)
                {
                    var wea = db.PRODUCTOS.Find(id);
                    Item wea2 = new Item();
                    wea2.Producto = wea;
                    wea2.Cantidad = 1;
                    cart.Add(wea2);
                }
                else
                {
                    cart[index].Cantidad++;
                }

                Session["cart"] = cart;
            }
            return View("Carrito");
        }

        public ActionResult CheckOut()
        {
            ViewBag.DEPARTAMENTOID = new SelectList(db.DEPARTAMENTOS, "ID", "NOMBRE");

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Checkout(FormCollection fc)
        {
            string[] DeptoID = fc.GetValues("DeptoID");
            string[] TrabajadorID = fc.GetValues("TrabajadorID");

            string Depto = DeptoID[0].ToString();

            int DID = Int32.Parse(DeptoID[0]);
            int TID = Int32.Parse(TrabajadorID[0]);

            Session["Departamento"] = DID;
            Session["Trabajador"] = TID;
            return View("Carrito");
        }

        public ActionResult Registrar()
        {
            ASIGNACIONES asignaciones = new ASIGNACIONES();
            var con = new SqlConnection("Data Source=DESKTOP-I5C9AA0\\SQLEXPRESS2008;Initial Catalog=InventarioUXBD;Integrated Security=True");
            con.Open();
            Item i = new Item();
            List<Item> cart = (List<Item>)Session["cart"];
            int preciototal = 0;
            asignaciones.EMPLEADOID = int.Parse(Session["ID"].ToString());
            int departamentoid = int.Parse(Session["Departamento"].ToString());
            int trabajadorid = int.Parse(Session["Trabajador"].ToString());
            asignaciones.DEPARTAMENTOID = departamentoid;
            asignaciones.Fecha = DateTime.Now;
            db.ASIGNACIONES.Add(asignaciones);
            db.SaveChanges();

            foreach (Item item in cart)
            {
                ASIGNACIONES_LISTA asignaciones_lista = new ASIGNACIONES_LISTA();
                asignaciones_lista.PRODUCTOID = item.Producto.ID;
                asignaciones_lista.PRECIO = item.Producto.PRECIO;
                preciototal = preciototal + (item.Producto.PRECIO * item.Cantidad);
                asignaciones_lista.ASIGNACIONID = asignaciones.ID;
                db.ASIGNACIONES_LISTA.Add(asignaciones_lista);
                db.SaveChanges();
                //Asigna nombre de depto al producto
                SqlCommand command2 = new SqlCommand("SELECT NOMBRE FROM DEPARTAMENTOS WHERE ID = " + departamentoid + "", con);
                string departamentonombre = (string)(command2.ExecuteScalar());
                SqlCommand command = new SqlCommand("UPDATE PRODUCTOS SET UBICACION = '" + departamentonombre + "' WHERE ID = " + item.Producto.ID + "", con);
                command.ExecuteNonQuery();
                //Asigna nombre de empleado al producto
                SqlCommand command3 = new SqlCommand("SELECT NOMBRE FROM TRABAJADORESUXes WHERE ID = " + trabajadorid + "", con);
                string trabajadornombre = (string)(command3.ExecuteScalar());
                SqlCommand command4 = new SqlCommand("UPDATE PRODUCTOS SET EMPLEADOASIGNACION = '" + trabajadornombre + "' WHERE ID = " + item.Producto.ID + "", con);
                command4.ExecuteNonQuery();
            }
            asignaciones.PRECIOTOTAL = preciototal;
            db.SaveChanges();
            Session.Remove("cart");
            Session.Remove("Departamento");
            Session.Remove("Trabajador");
            return View();
        }

        public ActionResult Cancelar()
        {
            return View("");
        }

        //public ActionResult Existencias()
        //{
        //    List<Item> cart = (List<Item>)Session["cart"];
        //    var con = new SqlConnection("Data Source=DESKTOP-I5C9AA0\\SQLEXPRESS2008;Initial Catalog=InventarioUXBD;Integrated Security=True");
        //    con.Open();
        //    int cont = 0;
        //    foreach (Item item in cart)
        //    {
        //        var command2 = new SqlCommand("SELECT CANTIDAD FROM dbo.ALMACENs WHERE PRODUCTOSID=" + item.Producto.ID + "", con);
        //        int existencia = (int)(command2.ExecuteScalar());
        //        if (item.Cantidad > existencia)
        //        {
        //            cont++;
        //        }
        //    }
        //    if (cont > 0)
        //    {
        //        return View("Error");
        //    }
        //    else
        //    {
        //        return RedirectToAction("Registrar");
        //    }
        // }

        public ActionResult Update(FormCollection fc)
        {
            var con = new SqlConnection("Data Source=DESKTOP-I5C9AA0\\SQLEXPRESS2008;Initial Catalog=InventarioUXBD;Integrated Security=True");
            con.Open();
            string[] cantidades = fc.GetValues("Cantidad");
            List<Item> cart = (List<Item>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
            {
                var command = new SqlCommand("SELECT CANTIDAD FROM PRODUCTOS WHERE ID='" + cart[i].Producto.ID + "'", con);
                int existencia = (int)(command.ExecuteScalar());
                if (Convert.ToInt32(cantidades[i]) > existencia)
                {
                    ViewBag.ErrorCantidad = true;
                    return View("Carrito");
                }
                else
                {
                    cart[i].Cantidad = Convert.ToInt32(cantidades[i]);
                }
            }
            return View("Carrito");
        }

        public ActionResult ReciboAsignacion(int? id)

InventarioUX/Views/CarritoAsignacion/Carrito.cshtml
@using InventarioUX.Controllers
@{
    ViewBag.Title = "Carrito";
}

<div>
    @Html.Partial("SelectProducto")
</div>

<h1>              </h1>
<h1>              </h1>

<table class="table">
    @using (Html.BeginForm("Update", "CarritoAsignacion", FormMethod.Post))
    {
        <input type="submit" class="btn btn-default" value="Actualizar cantidades" />
        <tr>
            <th>Eliminar</th>
            <th>ID</th>
            <th>Nombre</th>
            <th>Precio</th>
            <th>Cantidad</th>
            <th>Subtotal</th>
        </tr>
        if (Session["cart"] != null)
        {
            foreach (Item item in (List<Item>)Session["cart"])
            {
                <tr>
                    <th><button class="btn btn-default">@Html.ActionLink("Eliminar", "Eliminar", "CarritoAsignacion", new { id = item.Producto.ID })</button></th>
                    <th>@item.Producto.ID</th>
                    <th>@item.Producto.NOMBRE</th>
                    <th>@item.Producto.PRECIO</th>
                    <th><input type="text" name="Cantidad" , value="@item.Cantidad" /></th>
                    <th>@(item.Producto.PRECIO * item.Cantidad)</th>
                </tr>
            }
        }
        else
        {
            <tr>
                <th> </th>
                <th> </th>
                <th> </th>
                <th> </th>
                <th> </th>
                <th> </th>
            </tr>
        }
    }
</table>

<button class="btn btn-default">@Html.ActionLink("Generar Asignacion", "Registrar", "CarritoAsignacion", new { data_toggle = "modal", data_target = "#modalS" })</button>
<button class="btn btn-default">@Html.ActionLink("Cancelar Movimiento", "Index", "Account")</button>

<script src="~/Scripts/sweetalert2.js"></script>
<script src="~/Scripts/sweetalert2.min.js"></script>
<link href="~/Scripts/sweetalert2.css" rel="stylesheet" />
@if (ViewBag.Error == true)
{
    <script>
        window.onload = function () {
            swal(
                '¡El codigo de barras no existe!',
                'Ingrese un codigo de barras valido',
                'error'
            )
        };
    </script>
}

@if (ViewBag.ErrorCantidad == true)
{
    <script>
        window.onload = function () {
            swal(
                '¡Algun producto no cuenta con suficientes existencias!',
                'Porfavor revise las existencias de los productos ingresados en el campo "Existencias"',
                'error'
            )
        };
    </script>
}

<div class="modal fade" id="modalS" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        @using (Html.BeginForm())
        {
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Asignaciones</h4>
                </div>
                <div class="modal-body">
                    @Html.Partial("OrderSaved")
                </div>
                <div class="modal-footer">

                </div>
            </div>
        }
    </div>
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

InventarioUX/Views/CarritoAsignacion/CheckOut.cshtml
@model InventarioUX.Models.DeptoPuestoViewModel
@{
    ViewBag.Title = "CheckOut";
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
}

<h2>Seleccione un departamento</h2>

<fieldset>
        @using (Html.BeginForm("CheckOut", "CarritoAsignacion", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <table class="table">
                <tr>
                    <td>Departamento</td>
                    <td>@Html.DropDownListFor(model => model.DeptoID, ViewBag.DEPARTAMENTOID as SelectList, "-----Seleccionar Depto-----", new { @class = "form-control" })</td>
                    <td>Empleado</td>
                    <td>@Html.DropDownListFor(model => model.TrabajadorID, new SelectList(" "), "-----Select Depto-----", new { @class = "form-control" })</td>
                </tr>
                <tr>
                    <td>     </td>
                    <td><input type="submit" value="Ingresar" /></td>
                </tr>
            </table>
        }
</fieldset>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script>
    $(document).ready(function () {
        $("#DeptoID").change(function () {
            $.get("/CarritoAsignacion/GetStateById", { DeptoID: $("#DeptoID").val() }, function (data) {
                $("#TrabajadorID").empty();
                $.each(data, function (index, row) {
                    $("#TrabajadorID").append("<option value='" + row.ID + "'>" + row.NOMBRE + "</option > ")
                });
            });
        })
    });
</script>

InventarioUX/Views/CarritoAsignacion/Details.cshtml
@using InventarioUX.Models
@model InventarioUX.Models.ASIGNACIONES

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>MOV_ENTRADA</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CONTAINING_EMPLEADOS.USERNAME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CONTAINING_EMPLEADOS.USERNAME)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.CONTAINING_DEPARTAMENTOS.NOMBRE)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CONTAINING_DEPARTAMENTOS.NOMBRE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

    </dl>
</div>
<table class="table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Cantidad</th>
            <th>Precio</th>
            <th>Subtotal</th>
        </tr>
    </thead>


    @foreach (ASIGNACIONES_LISTA m in ViewBag.ListaAsignacion)
    {
        <tbody>
            <tr>
                <th>@m.CONTAINING_PRODUCTOS.NOMBRE</th>
                <th>@m.CANTIDAD</th>
                <th>@m.PRECIO</th>
                <th>@(m.PRECIO * m.CANTIDAD)</th>
            </tr>
        </tbody>
    }

    <tfoot>
        <tr>
            <th>Total</th>
            <th colspan="2"></th>
            <th id="total" colspan="2">@Html.DisplayFor(model => model.PRECIOTOTAL)</th>
        </tr>
    </tfoot>

</table>

<p>
    @Html.ActionLink("Back to List", "Index")
</p>

InventarioUX/Views/CarritoAsignacion/Existencias.cshtml
@{
    ViewBag.Title = "Existencias";
}

<h2>Existencias</h2>

InventarioUX/Views/CarritoAsignacion/Index.cshtml
@model IEnumerable<InventarioUX.Models.ASIGNACIONES>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "CheckOut")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.CONTAINING_DEPARTAMENTOS.NOMBRE)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.CONTAINING_EMPLEADOS.USERNAME)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.CONTAINING_DEPARTAMENTOS.NOMBRE)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CONTAINING_EMPLEADOS.USERNAME)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha)
            <td>
                @Html.ActionLink("Details", "Details", new { id = item.ID }) |
                @Html.ActionLink("Generar Recibo", "ExportPDF", new { id = item.ID })
            </td>
        </tr>
    }

</table>

InventarioUX/Views/CarritoAsignacion/OrderSaved.cshtml
<h2>Asignacion exitosa</h2>

@Html.ActionLink("Aceptar", "Index", "CarritoAsignacion", new { @class = "btn btn - success" })

InventarioUX/Views/CarritoAsignacion/ReciboAsignacion.cshtml
@using InventarioUX.Models
@model InventarioUX.Models.ASIGNACIONES
@{
    Layout = "~/Views/Shared/_LayoutRecibos.cshtml";
}
<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            Empleado:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CONTAINING_EMPLEADOS.USERNAME)
        </dd>

        <dt>
            Proveedor:
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CONTAINING_DEPARTAMENTOS.NOMBRE)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

    </dl>
</div>
<table class="table">
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Cantidad</th>
            <th>Precio</th>
            <th>Subtotal</th>
        </tr>
    </thead>


    @foreach (ASIGNACIONES_LISTA m in ViewBag.ListaAsignacion)
    {
        <tbody>
            <tr>
                <th>@m.CONTAINING_PRODUCTOS.NOMBRE</th>
                <th>@m.CANTIDAD</th>
                <th>@m.PRECIO</th>
                <th>@(m.PRECIO * m.CANTIDAD)</th>
            </tr>
        </tbody>
    }

    <tfoot>
        <tr>
            <th>Total</th>
            <th colspan="2"></th>
            <th id="total" colspan="2">@Html.DisplayFor(model => model.PRECIOTOTAL)</th>
        </tr>
    </tfoot>

</table>

InventarioUX/Views/CarritoAsignacion/SelectProducto.cshtml
@model InventarioUX.Models.PRODUCTOS

@using (Html.BeginForm("codigobarras", "CarritoAsignacion", FormMethod.Post))
{
    <div>
        <h5>Ingresar codigo de barras</h5>
        <input type="text" name="CodigoBarras" />
        <input type="submit" value="Agregar Producto" class="btn btn-default" />
    </div>
}